### ISSUE TITLE
Estructura contenedores

### ISSUE THREAD

**Issue by Azufer** [Zarritas/practica-integradora-Grupo1#1]
Hacer la estructura de los contenedores y las carpetas para poder subirlas a Git y compartirlas. Así todos tenemos las mismas.

**Comment by Zarritas** [comment]
Hecha la estructura simple del back/springboot

**Comment by Zarritas** [comment]
El proyecto de Vue vamos a hacerlo con Vue2 (es lo mismo) porq Vue 3 me esta generando problemas al instalar las dependencias

**Comment by Zarritas** [comment]
Estructura finalizada
